# -------------------------------------------------------
#                   Hammer build file
# -------------------------------------------------------
#       ,
#      /(  ___________
#     |  >:===========`
#      )(
#      ""
# Hammer is a simple tool for building C/C++ projects
# Hammer currently only knows how to build things with zig cc/c++
# -------------------------------------------------------
#
# Note that all the paths are relative in current directory
#
[compilation]
targets=["native", "aarch64-linux-musl", "aarch64-macos-gnu", "i386-linux-musl", "i386-windows-gnu", "x86_64-linux-musl", "x86_64-windows-gnu", "x86_64-macos-gnu"]
# -flto will also be added for non macos, windows targets automatically
args_c_or_cpp=["-O3", "-fPIC"]
args_cpp=["-std=c++17"]
args_c=["-std=c99"]
include_paths=["src", "3rd/utfcpp/source"]
# .c or .cpp files that get compiled to .o files
# so this is all except the .c/.cpp file with main()
sources=["src/ast/ast.cpp", "src/ast/ast_printer.cpp", "src/ast/ast_vis.cpp", "src/ast/codefiles.cpp", "src/ast/environment.cpp", "src/ast/environment_stack.cpp", "src/ast/parser.cpp", "src/builtins/builtins.cpp", "src/compiler/compiler.cpp", "src/compiler/compiler_utils.cpp", "src/compiler/def_class_visitor.cpp", "src/compiler/delete_stack.cpp", "src/compiler/delete_stack_stack.cpp", "src/compiler/entry_struct_compiler.cpp", "src/compiler/multifile_compiler.cpp", "src/compiler/type_checker.cpp", "src/file_formats/tokens_file.cpp", "src/tokenizer/block_analyzer.cpp", "src/tokenizer/string_utils.cpp", "src/tokenizer/tokenizer.cpp", "src/utilities/annotation.cpp", "src/utilities/annotations.cpp", "src/utilities/defer_stack.cpp", "src/utilities/defer_stack_stack.cpp", "src/utilities/ykdatatype.cpp", "src/utilities/ykdt_pool.cpp", "src/utilities/ykfunction.cpp", "src/utilities/ykobject.cpp"] # update_makefile.py HAMMER_CPP
temp_out_dir="bin/hammer"
binaries=["yakshac"]

[yakshac]
main_file="src/comp_main.cpp"
name="yakshac"
out_dir="bin/hammer.bin"
args_link=["-static", "-O3"]
