on: workflow_dispatch
env:
  PYTHONIOENCODING: utf-8
  PYTHONLEGACYWINDOWSSTDIO: utf-8

jobs:
  check-ubuntu-x86_64:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
    - name: Checkout git repo
      uses: actions/checkout@v4
      with:
        path: main
        submodules: 'true'
    - name: Preparations
      working-directory: main
      run: |
        git submodule init
        git submodule update
        sudo apt update
        sudo apt install -y docker
    - name: Test
      working-directory: main/compiler
      run: |
        ./cov
        zip -r coverage.zip ./bin/coverage
        zip -r failed.zip ./bin/fuzz
    - name: Upload coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: main/compiler/*.zip
  fuzz-check-ubuntu-x86_64:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
        with:
          path: main
          submodules: 'true'
      - name: Preparations
        working-directory: main
        run: |
          git submodule init
          git submodule update
          sudo apt update
          sudo apt install -y docker
      - name: Test
        working-directory: main/compiler
        run: |
          ./cov
          zip -r llvm-fuzz-coverage.zip ./bin/coverage
          zip -r llvm-fuzz-failed.zip ./bin/fuzz
      - name: Upload fuzz-coverage
        uses: actions/upload-artifact@v4
        with:
          name: fuzz-coverage
          path: main/compiler/*.zip