on: workflow_dispatch
env:
  PYTHONIOENCODING: utf-8
  PYTHONLEGACYWINDOWSSTDIO: utf-8

jobs:
  check-ubuntu-x86_64:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
    - name: Checkout git repo
      uses: actions/checkout@v2
      with:
        path: main
    - name: Preparations
      working-directory: main
      run: |
        # The 'submodules' option for actions/checkout@v2 doesn't
        # seem to work. So we manually sync it just in case.
        git submodule init
        git submodule update
        sudo apt update
        sudo apt install -y docker
    - name: Test
      working-directory: main/compiler
      run: |
        ./cov
        zip -r coverage.zip ./bin/coverage
        zip -r failed.zip ./bin/fuzz
    - name: Upload coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: main/compiler/*.zip
