on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  PYTHONIOENCODING: utf-8
  PYTHONLEGACYWINDOWSSTDIO: utf-8

jobs:
  check-macos-x86_64:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11]
    steps:
    - name: Checkout git repo
      uses: actions/checkout@v2
      with:
        path: main
    - name: Preparations
      working-directory: main
      run: |
        # The 'submodules' option for actions/checkout@v2 doesn't
        # seem to work. So we manually sync it just in case.
        git submodule init
        git submodule update
        sudo apt update
        brew install cmake ninja gcc p7zip
        mkdir -p compiler/cmake-build-release
    - name: Configuring CMake
      working-directory: main/compiler/cmake-build-release
      run: |
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ../
    - name: Build
      working-directory: main/compiler/cmake-build-release
      run: |
        ninja all
    - name: Test
      working-directory: main/compiler/cmake-build-release
      run: |
        ninja test
