on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  PYTHONIOENCODING: utf-8
  PYTHONLEGACYWINDOWSSTDIO: utf-8

jobs:
  check-ubuntu-x86_64:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    steps:
    - name: Checkout git repo
      uses: actions/checkout@v4
      with:
        path: main
        submodules: 'true'
    - name: Preparations
      working-directory: main
      run: |
        git submodule init
        git submodule update
        sudo apt update
        sudo apt install -y cmake ninja-build g++
        mkdir -p compiler/cmake-build-release
    - name: Configuring CMake
      working-directory: main/compiler/cmake-build-release
      run: |
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ../
    - name: Build
      working-directory: main/compiler/cmake-build-release
      run: |
        ninja all
    - name: Test
      working-directory: main/compiler/cmake-build-release
      run: |
        ninja test
