on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
env:
  PYTHONIOENCODING: utf-8
  PYTHONLEGACYWINDOWSSTDIO: utf-8
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11]
    steps:
    - name: Install 7z
      run: brew install p7zip
    - name: cmake
      run: brew install cmake
    - name: Checkout git repo
      uses: actions/checkout@v2
      with:
        path: main
        submodules: 'true'
    - name: Build zips & 7zs
      run: python main/compiler/scripts/release.py
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          main/compiler/comp_output_test/yaksha_v*.zip
          main/compiler/comp_output_test/yaksha_v*.7z